version: "{build}"

stack: python 3.10

environment:
  matrix:
  # For regular jobs, such as push, pr and etc.
  - job_name: Linux
    appveyor_build_worker_image: ubuntu1804
    GOARCH: amd64

for: 
  - # Linux
    build: off
    matrix:
      only:
        - job_name: Linux

    install:
      - sudo apt update
      - sudo apt-get install -y python3-pip
      - sudo pip3 install mkdocs
      - sudo pip3 install mkdocs-material==7.3.4
      - sudo pip3 install mkdocs-git-revision-date-plugin
      - sudo pip3 install mkdocs-macros-plugin
    branches:
      only:
        - main
    deploy:
      - provider: script
        on:
          branch: main
    before_deploy:
      - git config user.name "jdknives";
      - git remote add gh-token "https://${GITHUB_TOKEN}@github.com/skycoin/wiki.git";
      - git fetch gh-token && git fetch gh-token gh-pages:gh-pages
      - mkdocs gh-deploy -v --clean --remote-name gh-token;
    deploy_script:
      - echo "Completed!"
