site_name: Skycoin Wiki
site_description: >-
  Welcome to our wiki! Navigate with the buttons below or search for a keyword.

header_news: >-
  !!! This wiki is in <span style="color:MediumSeaGreen;"><b>ALPHA</b></span> state. There may be outdated data. If you find errors please use the <span style="color:Tomato;">issue / edit feature</span> on the right upper corner of each site   !!!

nav:
      - Home: index.md
      - Software:
        - Overview:                   software\index.md
        - Skycoin: 
          - Overview:                 software\skycoin\index.md
          - About:                    software\skycoin\about.md
          #- Setup:                   
          #- User Docs: 
          #- Dev Docs: 
          - Social:                   software\skycoin\social.md
          - Explorer:                 https://explorer.skycoin.com/app/blocks/1       

        - Fiber:                        
          - Overview:                 software\fiber\index.md
          #- About:
          #- Setup:
          #- User Docs:
          #- Dev Docs:
          - Fiber-Projects:           software\fiber\fiber-coins.md

        - Skywire:
          - Overview:                 software\skywire\index.md        
          - About:                    software\skywire\about.md
          - Setup: 
              - Overview:             software\skywire\setup\overview.md
              - Windows:              software\skywire\setup\windows.md
              - macOS:                software\skywire\setup\macos.md
              - Linux:                software\skywire\setup\linux.md
              - Raspberry Pi & SBCs:  software\skywire\setup\raspberrypi.md
              - Docker:               software\skywire\setup\docker.md
          - User Docs:
              - Overview:             software\skywire\userdocs\overview.md
              - Rules:                software\skywire\userdocs\rules.md
              - Authentication:       software\skywire\userdocs\authentication.md
              - Whitelisting:         software\skywire\userdocs\whitelisting.md
              - Apps:
                - Overview:           software\skywire\apps\overview.md
                - Proxy:              software\skywire\apps\proxy\userdoc.md
                - Skychat:            software\skywire\apps\skychat\userdoc.md
                - VPN:                software\skywire\apps\vpn\userdoc.md              
          - Dev Docs:
              - Overview:             software\skywire\devdocs\overview.md
              - Architecture:         software\skywire\devdocs\architecture.md 
              - Transports:           software\skywire\devdocs\transports.md
          - Social:                   software\skywire\social.md
          - Discovery & Uptime:       software\skywire\discovery.md

        - CX:
          - Overview:                 software\cx\index.md
          - About:                    software\cx\about.md
          - Setup:
            - Overview:               software\cx\setup\overview.md
            - Windows:                software\cx\setup\windows.md
            - macOS:                  software\cx\setup\macos.md
            - Linux:                  software\cx\setup\linux.md
            - Programming Tools:
              - VS Code:              software\cx\setup\vscode.md
              - Emacs:                software\cx\setup\emacs.md
              - Atom:                 software\cx\setup\atom.md
          - User Docs:
              - Overview:             software\cx\userdocs\overview.md
              - Basics:
                - Syntax:             software\cx\userdocs\basics-syntax.md
                - Runtime:            software\cx\userdocs\basics-runtime.md
                - Native Functions:   software\cx\userdocs\basics-native-functions.md
                - Running CX:         software\cx\userdocs\basics-running-cx.md
                - REPL:               software\cx\userdocs\basics-repl.md
              - Native Packages:
                - time:               software\cx\userdocs\package-time.md
                - os:                 software\cx\userdocs\package-os.md
                - gl:                 software\cx\userdocs\package-gl.md
                - glfw:               software\cx\userdocs\package-glfw.md
                - gltext:             software\cx\userdocs\package-gltext.md
          #- Dev Docs:
          - Social:                   software\cx\social.md
          - CX Tracker:               https://cx-tracker.skycoin.com/

        - CXO: 
          - Overview:                 software\cxo\index.md        
          - About:                    software\cxo\about.md
          #- Setup:
          #- User Docs:
          #- Dev Docs:
          #- Social:
          - CXO Tracker:              https://cxo.skycoin.com/

        - CXFX:                        
          - Overview:                 software\cxfx\index.md
          - About:                    software\cxfx\about.md
          #- Setup:
          #- User Docs:
          #- Dev Docs:
          #- Social:
          - Roadmap:                  software\cxfx\roadmap.md

        #- DMSG:                      software\dmsg\index.md
          #- Overview:                software\dmsg\overview.md
          #- About:                   software\dmsg\about.md
          #- Setup:
          #- User Docs:
          #- Dev Docs:
          #- Social:

        #- Teller:

        #- KittyCash:                 https://kittycash.io/home


      - Hardware:
        - Overview:                             hardware\index.md
        - Skyminer:
          - Overview:                           hardware\skyminer\index.md
          - About:                              hardware\skyminer\about.md
          - Userdocs:
            - Assembly:                         hardware\skyminer\assembly.md
            - Software:                         hardware\skyminer\setup.md
            - Networking:                       hardware\skyminer\networking.md
            #- User Docs:
          #- Dev Docs:
          #- Social:
        
        - Skywallet:
          - Overview:                           hardware\skywallet\index.md
          - About:                              hardware\skyminer\about.md
          #- Setup:
          - User Docs:
            - Manual:
              - Checking the genuineness:       hardware\skywallet\userdocs\manual\01-checking-the-genuineness.md
              - Initializing the wallet:        hardware\skywallet\userdocs\manual\02-initializing-the-wallet.md
              - Personalizing the wallet:       hardware\skywallet\userdocs\manual\03-personalizing-the-wallet.md
              - Firmware update:                hardware\skywallet\userdocs\manual\04-firmware-update.md
              - Testing your seed:              hardware\skywallet\userdocs\manual\05-testing-your-seed.md
              - Restoring backup:               hardware\skywallet\userdocs\manual\06-restoring-backup.md
              - Optimizing the security:        hardware\skywallet\userdocs\manual\07-optimizing-the-security.md
              - Sending and Receiving coins:    hardware\skywallet\userdocs\manual\08-sending-and-receiving-coins.md
              - Miscellaneous operations:       hardware\skywallet\userdocs\manual\09-miscellaneous-operations.md
              - Troubleshooting:                hardware\skywallet\userdocs\manual\10-troubleshooting.md
          #- Dev Docs:
          #- Social:

        - Skywallet DK:                         hardware\skywalletdk\index.md

      - Skyfleet: 
        - Overview:             skyfleet\overview.md
        - Captain Sky:          skyfleet\captain-sky-comics.md
        - Brand:                skyfleet\brand.md
        - Videos:               skyfleet\videos.md

      - More:
        - Exchanges:            exchanges.md
        - Use SKY/SCH:          buywithsky.md
        - Brand:                brand.md     

      - News:         news.md
      - Meetups:      meetups.md
      - Media:        videos.md
      - Partnerships: partnerships.md
      - Contribute:   contribute.md
      - Roadmap:      roadmap.md
      - Timeline:     timeline.md
      - About:        about.md

theme: 
  name:       material
  custom_dir: overrides
  logo:       img/Skycoin-Cloud-White.png
  favicon:    img/Skycoin-Cloud-Blue.png
  features:
    - header.autohide
    - navigation.instant #landing page crashes atm when activated
    - navigation.tabs
    - toc.autohide

extra_css:
  - stylesheets/extra.css

plugins:  
  - git-revision-date
  - search
  - macros

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.skycoin.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Skycoinproject
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/skycoin
    - icon: fontawesome/brands/telegram
      link: https://t.me/Skycoin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EgBenrW
    - icon: fontawesome/brands/medium
      link: https://medium.com/skycoin
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/skycoin
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/skycoinproject/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_rRSG_Db1D-rnmU20b_kRg
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SkycoinOfficial/
      
  issue_url: https://github.com/skycoin/wiki/issues

repo_url:   https://github.com/skycoin
repo_name:  github.com/skycoin
edit_uri:   wiki/blob/master/docs/